import { StyleSheet } from 'react-native'
import { COLORS,SIZES } from '../constants'
const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:COLORS.lightwhite,
    },
    upperRow:{
        marginHorizontal:20,
        flexDirection:"row",
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        position:"absolute",
        top:SIZES.xSmall-2,
        width:SIZES.width -44,
        zIndex:999
    },
    image:{
        aspectRatio:1,
        resizeMode:'cover',
    },
    details:{
        marginTop:-SIZES.large,
        backgroundColor:COLORS.lightwhite,
        width:SIZES.width,
        borderTopLeftRadius:SIZES.medium,
        borderTopRightRadius:SIZES.medium,
    },
    titleRow:{
        marginHorizontal:20,
        paddingBottom:SIZES.small,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        width: SIZES.width -44,
        top:20

    },
    title:{
        fontFamily:"bold",
        fontSize:SIZES.large,
    },
    ratingRow:{
        paddingBottom: SIZES.small,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        marginHorizontal:SIZES.large
    },
    rating:{
        top:SIZES.large,
        flexDirection:"row",
        alignItems:"center",
        marginHorizontal:SIZES.large
    },
    ratingText:{
        color:COLORS.gray,
        fontFamily:"medium",
        paddingHorizontal:SIZES.small,
    },
    price:{
        paddingHorizontal:10,
        fontFamily:"semibold",
        fontSize:SIZES.large,
    },
    priceWrapper:{
        backgroundColor:COLORS.secondary,
        borderRadius:SIZES.large,
    },
    descriptionWrapper:{
        marginTop:SIZES.large+2,
        marginHorizontal:SIZES.large,
    },
    description:{
        fontFamily:"medium",
        fontSize:SIZES.large-2,
    },
    descText:{
        fontFamily:"regular",
        fontSize:SIZES.small,
        textAlign:"justify",
        marginBottom:SIZES.small
    },
    location:{
        flexDirection:"row",
        justifyContent:"space-between",
        padding:5,
        borderRadius:SIZES.large,
        alignItems:"center",
        backgroundColor:COLORS.secondary,
        marginHorizontal:12,
    },
    cartRow:{
        paddingBottom:SIZES.small,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        width: SIZES.width-30 ,
    },
    cartBtn:{
        width:SIZES.width*0.6,
        backgroundColor:COLORS.black,
        padding:SIZES.small/2,
        borderRadius:SIZES.large,
        marginLeft:8,
    },
    cartTitle:{
        marginLeft:SIZES.small,
        fontFamily:"regular",
        fontSize:SIZES.medium,
        color:COLORS.white,
    },
    addCart:{
        width:37,
        height:37,
        borderRadius:50,
        margin:SIZES.small,
        backgroundColor:COLORS.black,
        alignItems:"center",
        justifyContent:"center"
    }
})

export default styles